services:  
  postgres:  
    image: postgres:15  
    ports:  
      - "5432:5432"  
    environment:  
      POSTGRES_USER: user  
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: taskdb  
    volumes:  
      - postgres-data:/var/lib/postgresql/data  
volumes:  
  postgres-data:  